// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASe885HNBSDn8FEr-8D7YLEQczyHepbbM',
    appId: '1:617253659263:web:d8bdcaae1c73103387954a',
    messagingSenderId: '617253659263',
    projectId: 'fluttershare-5cbe6',
    authDomain: 'fluttershare-5cbe6.firebaseapp.com',
    databaseURL: 'https://fluttershare-5cbe6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-5cbe6.firebasestorage.app',
    measurementId: 'G-1RKP4C1ZBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf4ypheEKe4qC2noFmFwj5rankTt8exGc',
    appId: '1:617253659263:android:6cb2d52298093a1087954a',
    messagingSenderId: '617253659263',
    projectId: 'fluttershare-5cbe6',
    databaseURL: 'https://fluttershare-5cbe6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-5cbe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKo-M6k1rG-khM-U3ux5dBHbWS5Pjn-c',
    appId: '1:617253659263:ios:b3b48557e014595487954a',
    messagingSenderId: '617253659263',
    projectId: 'fluttershare-5cbe6',
    databaseURL: 'https://fluttershare-5cbe6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-5cbe6.firebasestorage.app',
    androidClientId: '617253659263-cjs2s4s534aapdbb3r0t298c0ltncu5q.apps.googleusercontent.com',
    iosClientId: '617253659263-2pqh2aveuh663nvv6mnbts404707h2cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKo-M6k1rG-khM-U3ux5dBHbWS5Pjn-c',
    appId: '1:617253659263:ios:b3b48557e014595487954a',
    messagingSenderId: '617253659263',
    projectId: 'fluttershare-5cbe6',
    databaseURL: 'https://fluttershare-5cbe6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-5cbe6.firebasestorage.app',
    androidClientId: '617253659263-cjs2s4s534aapdbb3r0t298c0ltncu5q.apps.googleusercontent.com',
    iosClientId: '617253659263-2pqh2aveuh663nvv6mnbts404707h2cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASe885HNBSDn8FEr-8D7YLEQczyHepbbM',
    appId: '1:617253659263:web:6410d9915e9de21187954a',
    messagingSenderId: '617253659263',
    projectId: 'fluttershare-5cbe6',
    authDomain: 'fluttershare-5cbe6.firebaseapp.com',
    databaseURL: 'https://fluttershare-5cbe6-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-5cbe6.firebasestorage.app',
    measurementId: 'G-VXD5V55SBT',
  );

}